name: Compile SWOT
on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths: [ 'docs/**' ]
  pull_request:
    branches: [ master ]
    paths: ['docs/**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Go to 'docs' Folder
        run: cd docs
      - name: Compile Report
        uses: dante-ev/latex-action@v0.2.0
        with:
          root_file: documentation.tex
          args: -lualatex -latexoption=-file-line-error -latexoption=-interaction=nonstopmode
      - name: Upload Compiled Report
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: docs/documentation.pdf
